version: '3'
services:

  go-api:
    image: go-api
    container_name: go-api
    env_file:
      - .env
    build: ./
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - go-network
    volumes:
      - ./:/go-api
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - go-network      
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  

networks:
  go-network:
    driver: bridge