version: '3'
services:
  go-api-postgres:
    image: "postgres"
    container_name: go-api-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=go-api
    ports:
      - "5432:5432"
    networks:
      - bridge
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  

  go-api:
    image: golang:latest
    container_name: go-api
    build: ./
    ports:
      - 8080:8080
    networks:
      - bridge
    volumes:
      - ./:/go-api
    depends_on:
      - go-api-postgres

