version: '3'
services:

  app:
    image: hahndev/go-api:latest
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    networks:
      - frontend
      - backend
    volumes:
      - app:/app
    depends_on:
      - db
    links:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  backend:
    driver: overlay
  frontend:
    driver: overlay
    
volumes:
  app:
  data: